### ISSUE TITLE
Audio chat example low volume?

### ISSUE THREAD

**Issue by Therealjosephchrzempiec** [networked-aframe/networked-aframe#429] opened 2023-09-14 21:15 UTC
Hello, I been trying the audio chat on my iphone 11 pro max. Audio seems to work. however when I listen from the phone and talk from my laptop the audio on my iphone seems to be very low. I can here it but barely. Is this knows by others or how can I fix it to increase it?

Joseph

**Comment by vincentfretin** [comment] 2023-09-16 07:44
Hello, it's a known issue, but I have no idea what the issue is, there was an attempt in #418 to fix it but I don't own an iPhone so I can't really debug this issue.

**Comment by ahmedrana3d** [comment] 2024-01-16 11:55
@Therealjosephchrzempiec I was the first who had this issue on IOS, I confirmed this with testing this on multiple IOS devices. Few days ago I tested the same app again and this time the audio was alright I don't know how, I tested this with my colleague and we were able to listen eachother perfectly, I don't think so @vincentfretin did something, I want you test again on your IPhone to confirm if the issue is resolved, maybe it is fixed after IOS update, no idea.

**Comment by vincentfretin** [comment] 2024-01-16 15:33
No I did nothing. That's great if this is fixed now on latest iOS. It's iOS 17.2 right now.
If you can confirm the iOS version and if it's really fixed, that would be great.

**Comment by vincentfretin** [comment] 2024-01-19 09:15
I guess it was probably a temporary issue with glitch. What about now?
@Therealjosephchrzempiec When you have time can you also please test again with iOS 17.2 on your iPhone?

**Comment by Therealjosephchrzempiec** [comment] 2024-01-19 09:18
Hey I’m sorry I have not been home. I had to fly back to my parents place.
I just lost my father. I’ll check glitch in the morning.

**Comment by vincentfretin** [comment] 2024-01-19 09:25
I'm sorry to hear that, my condolences.

There is no hurry to test that. It's just to confirm if the issue is fixed so I can close it. Even if the issue is still there, I probably can't do much about it.

**Comment by Therealjosephchrzempiec** [comment] 2024-01-19 09:31
He's not my dad. He's my best friend. I grew up with dad. My dad was a
workaholic so I spent a lot of time at his house and he spent a lot of time
at my house. His mom is my second mom and his dad is my second dad.

**Comment by Therealjosephchrzempiec** [comment] 2024-01-19 09:32
I'll be back tomorrow. Do you have time on Saturday morning?

**Comment by Therealjosephchrzempiec** [comment] 2024-01-20 13:11
I went to the site from my computer and my phone but no microphones are working.

**Comment by ahmedrana3d** [comment] 2024-01-20 13:43
What do you mean? you cannot hear any audio or that the volume is still low?

**Comment by Therealjosephchrzempiec** [comment] 2024-01-20 21:06
When I go to it from my phone either in the basic browser that iphone comes with or in chrome I can not see anyone else or hear anything at all. I tried it on the same wifi network and I tried it on my phone mobile network. I get the same results. The addressers are the same, The scene is the same.

**Closed** 2024-03-13 17:25 UTC
