### ISSUE TITLE
Avatars disappear in demos

### ISSUE THREAD

**Issue by osresearch** [networked-aframe/networked-aframe#200] opened 2020-05-15 19:29 UTC
I've setup the demos in a clean checkout with a nginx reverse proxy doing SSL termination and it almost works perfectly. In the basic and tracked controller demo, however, users (including VR headsets) can connect to the room and see the other players, but after a little while some of the other avatars disappear from view (but not from the occupants array).  It's often very disjoint as to who can still see who. Reloading the page fixes things for a little while. 

There is an error on the console about `this.data` being undefined in `networkUpdate()`, but it appears before the users start disappearing. There don't appear to be any console messages when the avatars go missing.

Any ideas for what might be happening?

**Comment by osresearch** [comment] 2020-05-15 19:35
This happens with both `adapter: socketio` and `adapter: webrtc`.

**Comment by mneunomne** [comment] 2020-05-15 22:28
I have exactly the same error in my application. I am currently using socketio adapter.
After the error the client keeps disconnecting from the server with the reason being "ping timeout".

**Comment by mneunomne** [comment] 2020-05-15 23:33
I was able to consistently reproduce this error by connecting a mobile device and be constantly moving the gyroscope so there is always an updating happening in the scene. While i do that and try to connect another client, "this.data" is undefined from the update coming from that mobile client.

I was able to make avoid this exception by simply returning the function if `data` is undefined with the following code on line 409 in the `src/components/networked.js` file:

` if (this.data === undefined) {
      return
    }`

Apparently `this.data` is undefined for a couple of times while this function is called, then the component seems to be correctly loaded. Maybe it is an issue of receiving updates from a component that was not yet locally loaded ?

Surely there is a better solution than this little hack i made, but it's temporarily working for me  😅.

Cheers!

**Comment by osresearch** [comment] 2020-05-24 12:24
The patch in #202 might not have fixed it, unfortunately.  With the fix applied and using webrtc, sometimes avatars disappear, although it seems very asymmetric since they can still see the other players. On the console of the computer that no longer sees the other there is a message:

```
Closed data channel from goE7AIlw7E6ZeiG5AAAF
```

**Comment by vincentfretin** [comment] 2021-02-22 10:50
Still with socketio? This seems that the socket timed out and closed, no? You may need to send regularly something in the socket so it stays alive.

**Comment by vincentfretin** [comment] 2021-02-23 20:16
Yes, I confirm that the socketio/webrtc adapters in this repository lack any sort of keepalive message, so if there is no component updates going through the socket like maybe for 30s (it depends on the keepalive param in nginx or apache for example), the websocket will just close. Please use the easyrtc/wseasyrtc adapters with open-easyrtc, it's sending a stillAlive message every 20s.

I'll just close the issue as wontfix I think, I don't see any value maintaining socketio/webrtc adapters really. I'll mark the socketio/webrtc adapters as wip or remove them from the repo in #240

**Closed by vincentfretin** 2021-02-23 20:16 UTC
Labels: wontfix

**Comment by vincentfretin** [comment] 2021-02-24 07:31
I won't be removing them mainly because I currently don't have the permissions to move the code to the other repositories in the networked-aframe organization yet. The socketio/webrtc adapters will stay in the repository for the time being, I think they have some value as a learning purpose, mainly the server part, but I won't maintain those. I'll mark them as non production ready. You are free to create a PR for the socketio/webrtc adapters to implement some sort of keepalive similar to how it's done in open-easyrtc, I'll review and merge it, but I won't work on it myself.

**Comment by vincentfretin** [comment] 2024-12-01 18:53
fyi this original issue came back in aframe 1.6.0, see #476
