### ISSUE TITLE
Clients Not Visible in WebVR on Samsung Internet

### ISSUE THREAD

**Issue by DaveBben** [networked-aframe/networked-aframe#34] opened 2017-08-11 17:19 UTC
Using the Galaxy S8 on Google Chrome I can view other clients. But when using Samsung WebVR, no other clients are visible and the server doesn't even detect me connecting. WebRTC is set to false.

**Comment by haydenjameslee** [comment] 2017-08-14 12:26
I was able to reproduce this too. Looking into it.

**Comment by haydenjameslee** [comment] 2017-08-14 12:54
Paging @adaroseedwards! Any ideas?

**Comment by AdaRoseEdwards** [comment] 2017-08-14 13:31
Is this using Samsung Internet for GearVR?
What is the version number?

It is possible to debug the VR browser remotely over the network the instructions are at the bottom of the page here: https://samsunginter.net/docs/remote-debugging

**Comment by poshaughnessy** [comment] 2017-10-22 22:37
I've replicated this with both the 'basic' and 'basic-events' demos I've tried, in both the current version of Samsung Internet for Gear VR and the current stable version of Samsung Internet for Android, v5.4. (So it doesn't appear to just be an issue when using the WebVR mode, but in the regular mobile view too).

Debugging as Ada suggested, this is the error I'm seeing: `Illegal invocation`

<img width="969" alt="screen shot 2017-10-22 at 23 20 11" src="https://user-images.githubusercontent.com/151207/31867066-a93fd20a-b780-11e7-84c8-4009115f4edc.png">

The arguments being passed to the `fireEvent` method that the error refers to are:
* `el`: the `a-scene` element
* `name`: `render-target-loaded`
* `data`: `{bubbles: true, detail: {target: canvas.a-canvas ...`

I need to check with colleagues what the cause is, but the good news is that I've checked in our Samsung Internet for Android v6.2 Beta and it appears to be fixed there. This should be getting released to stable very soon. As for a fix for the Gear VR version of the browser, I'll check with our colleagues and hope to get back to you soon.

**Comment by haydenjameslee** [comment] 2017-10-23 01:02
Really appreciate the help @poshaughnessy!

**Comment by vincentfretin** [comment] 2021-02-23 09:57
This issue is quite old, and I think Samsung Internet and Oculus browser switched to WebXR since then. Even if this was still an issue, we can't do anything about it, GearVR is not supported anymore, and Samsung Internet or Oculus browser doesn't get update on it anymore. I'm sure about Oculus browser, and @AdaRoseCannon can confirm if it's the case for Samsung Internet as well. So I'm just closing it.

**Closed by vincentfretin** 2021-02-23 09:57 UTC
Labels: bug
