### ISSUE TITLE
easyrtc and pc avatars vs non-pc avatars not showing 

### ISSUE THREAD

**Issue by mikashki** [networked-aframe/networked-aframe#333] opened 2022-04-07 12:13 UTC
Are there any known issues with AR/VR users (Samsung & Oculus browsers) and PC users (Chrome and Edge browsers) not seeing the avatars of all other participants when using the **easyrtc adapter** in NAF? 

Case example: 

The Google Blocks example app which uses socket.io adapter by default (I guess) and when both PC users and AR or VR users connect to it, they all see each other's avatars just fine.  

But if you change the networked-scene adapter to easyrtc (in the Google Blocks example, no other changes to the scene or entities), what happens is that PC and AR/VR users don't all see each other's avatars anymore. Usually the AR/VR users don't see some or all the PC users or each other. On the other hand PC users see both the AR and VR user avatars. 

In my case the PC users are Chrome and Edge browsers and the AR user is a Samsung Internet browser and VR user is an Oculus browser on Quest1. I'm running the examples on localhost (the PC) and using adb reverse proxying from the Samsung phone and Quest to access the localhost server on the PC. The server log on the PC shows that the different users do connect to it, it's just that the AR/VR users don't see the other avatars. 

I was wondering if the reverse proxying has something to do with this issue, or if running this on localhost server in general might be the culprit, but I'm seeing the same issue also on e.g. https://acoustic-curly-enthusiasm.glitch.me/ if I connect to it with the same browsers. PC users (usually) see all the avatars in the room, also AR or VR avatars moving their heads, but the AR/VR users don't. 

Possibly a browser compatibility issue with the Samsung Internet and Oculus browsers? Or something in open-easyrtc? Or the adapter in NAF? Anyone else seen or reported this kind of issues with the easyrtc adapter? The default socket.io adapter seems to work fine, all users see all other avatars, but it doesn't support audio transport which I'd like to achieve by using the easyrtc adapter.

**Comment by vincentfretin** [comment] 2022-04-07 13:00
I don't use easyrtc in any project and don't use the headset much so I don't know if there is a real issue or not. Maybe someone else using the easyrtc adapter can give feedback here.

The default adapter is wseasyrtc when networked-scene adapter is not specified (for Google Blocks example), otherwise the examples specify explicitly wseasyrtc or easyrtc if audio/video is used. None of the examples are using the socketio adapter unless you start the socketio specific server with `npm start-socketio` and set adapter:socketio yourself.
The wseasyrtc adapter is using open-easyrtc and socketio only, no WebRTC involved.

If you don't have any issue with wseasyrtc, but only with easyrtc adapter, the issue is probably WebRTC related.
All participants are on the same network? If not, maybe some participants needs to go through a turn server?

With the easyrtc adapter, I think the user is really connected to the room if they has a valid mic (to be confirmed). Did you accept the mic permission properly?
Do you see anything unusual in the console logs when you run the Chrome inspector remote devices (after you set the proxy with adb)?

Be sure that when you're testing, if your restart the server, that all participants refresh their page, see #242

**Comment by mikashki** [comment] 2022-04-07 13:52
Thanks for the quick response and clarification on the adapters used. 

The microphone permissions were okay yes, but the same network... Aargh. 

Turns out the issue in the localhost environment was that all devices were on different Wifi networks, I have three different SSIDs / base stations in the house and each device (laptop, phone and VR headset) were using different ones. Switching them all to the same wifi network resolved the issue of some avatars not being visible to some of the users. What an odd issue.  I guess some signaling didn't carry across the wifi segments and caused the avatars to become invisible. 

Next I need to test that the audio transport actually works, but I read somewhere in the docs that it requires an https connection?

**Comment by vincentfretin** [comment] 2022-04-07 14:32
Yes you can create a certificate with https://github.com/FiloSottile/mkcert and modify server/easyrtc-server.js to reference it, see #257

**Comment by vincentfretin** [comment] 2022-04-08 08:18
I'm closing the issue then.

**Closed by vincentfretin** 2022-04-08 08:18 UTC
