### ISSUE TITLE
EasyRTC bug, i can see other players but they can't see me or vice versa

### ISSUE THREAD

**Issue by AdaRoseCannon** [networked-aframe/networked-aframe#338] opened 2022-05-06 22:46 UTC
I have a weird issue where when doing connections between devices e.g. laptop to headset or headset to headset often one of the connections only works one way. I.e.

* laptop user sees user on headset 1 but not headset 2
* User on headset 1 sees headset 2 but not laptop
* headset 2 user doesn't see either

I'd understand if one headset was totally disconnected it would mean a route couldn't be made but often its like a one way connection. I'm not sure if I have something weird in my configuration it's not too different from the example code.

Also the audio doesn't work but I assume it's a related issue.

url: https://my-metaverse.glitch.me

**Comment by vincentfretin** [comment] 2022-05-07 08:08
I don't see anything wrong in your example, you're using latest networked-aframe, you specified `adapter:easyrtc` and glitch is on https so you should have audio working.
Do you reproduce the issue on https://naf-examples.glitch.me/basic-audio.html ?
Ah I spotted an error, `networked-audio-source` should be in your `head-template`, not your avatar-head, you actually don't need the component for your own avatar. Every remote avatar needs to have the component.
```
        <template id="head-template">
          <a-entity networked-audio-source>
            <a-entity class="avatar-head">
              <a-gltf-model shadow class="head-model" rotation="0 180 0" position="0 -0.2 0" scale="0.8 0.8 0.8" src="[#head-avatar-a-gltf](view-source:https://my-metaverse.glitch.me/#head-avatar-a-gltf)" update-gltf-model="sync:true"></a-gltf-model>
            </a-entity>
          </a-entity>
        </template>
```

Are you sure you're using the same Wi-Fi network between your devices? If you're not using the same network, one of your device may need a turn server?
I just tested the example with two desktop and my Quest on the same Wi-Fi network, it worked properly.

I love the golden hands :) but how do I exit the VR mode lol? In your other example you had the exit on your wrist, that was cool.

**Comment by AdaRoseCannon** [comment] 2022-05-07 08:17
I should re-add the wrist exit button it is really convenient for testing. Glad I seem to be doing everything okay.

Yeah often the errors show up in weird situations where one person is tethering and the other is in the conference wifi.

Is there a simple pre configured turn server service that one can pay for? It's not really my area of expertise. 

Otherwise it would be really handy if there is a backend which uses websockets for syncing and webrtc for audio.

**Comment by vincentfretin** [comment] 2022-05-07 08:29
Someone had a similar issue with local network #333 in the end it was because the device was not on the same Wi-Fi network.
For turn server, you can use xirsys free plan it's great, see documentation https://github.com/networked-aframe/networked-aframe/blob/master/docs/hosting-networked-aframe-on-a-server.md#extra-steps-for-webrtc

**Comment by vincentfretin** [comment] 2022-05-07 08:34
> Otherwise it would be really handy if there is a backend which uses websockets for syncing and webrtc for audio.

This is a feature request I created for the easyrtc adapter #324
The janus adapter (can't be used with glitch, you need your own VM to run the janus sfu) can be used with websocket for naf transport and webrtc for audio, but you will be rejected of the room if the webrtc connection is not successful, so you need to configure properly a turn server anyway.

**Comment by AdaRoseCannon** [comment] 2022-05-07 08:46
Ah cool good to know thank you! Thanks for all your help!

**Comment by vincentfretin** [comment] 2022-05-07 08:54
I'll close the issue then. You can still comment on this issue if you have other questions. I'm also available on aframe slack or discord if you want to chat.

**Closed by vincentfretin** 2022-05-07 08:54 UTC
